# Generated by Django 5.2.5 on 2025-08-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('tsubject', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
